### ISSUE TITLE
mllmTeam/PhoneLM-0.5B-Instruct model

### ISSUE THREAD

**Issue by lyupei** [UbiquitousLearning/PhoneLM#1]
Hi, I guess the mllmTeam/PhoneLM-0.5B-Instruct model.safetensor is wrong, cause the file size and model structure is as same as 1.5B model

**Comment by yirongjie** [comment]
Thank you for your attention, I have updated: https://huggingface.co/mllmTeam/PhoneLM-0.5B-Instruct
